sudo: false
dist: trusty

# prevent travis from recursive gitsubmodule checkout
git:
  submodules: false

addons:
  chrome: stable

before_script:
  - export DISPLAY=:99.0
  - curl -Lo chromedriver.zip http://chromedriver.storage.googleapis.com/2.30/chromedriver_linux64.zip && unzip chromedriver.zip
  - sh -e /etc/init.d/xvfb start
  - sleep 4
  - npm run build &
  - sleep 8
  - npm run server &
  - sleep 8
  - firefox http://localhost:5777/utest/ &
  - sleep 8

script:
  - "npm test"

language: node_js
node_js:
  - "8.0.0"
compiler: clang-3.4
env:
  - CXX=clang-3.4
